# 支持本项目
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Digidai]
# ko_fi: # your-ko-fi-username
# buy_me_a_coffee: # your-buymeacoffee-username
# custom: ['https://example.com/sponsor']
