# 如需支持项目发展，可配置以下赞助渠道
# github: [daidai2025]
# patreon: # your-patreon-username
# open_collective: # your-open-collective-username
# ko_fi: # your-ko-fi-username
# custom: ['https://example.com/donate']
